const PDFDocument = require('pdfkit');

function formatPaise(paise) {
  if (paise == null) return 'N/A';
  return `₹${Math.round(paise / 100).toLocaleString('en-IN')}`;
}

function heading(doc, text) {
  doc.moveDown(1).fontSize(14).fillColor('#111').text(text, { underline: true });
  doc.moveDown(0.3).fontSize(11).fillColor('#333');
}

function keyValue(doc, label, value) {
  if (value == null || value === '') return;
  doc.text(`${label}: ${value}`);
}

// Renders a LocalityInsight (+ live inventory stats, from getLocalityPage) into a
// PDF buffer. Kept to plain structured text — no charts/AI — since the source
// data (priceTrends, connectivity, prosAndCons, etc.) is already structured JSON.
function buildLocalityReportPdf(page) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).fillColor('#111').text(`${page.locality}, ${page.city}`, { align: 'left' });
    doc.fontSize(11).fillColor('#666').text(page.subtitle || 'Locality Market Report');
    doc.moveDown(0.5).fontSize(9).fillColor('#999')
      .text(`Data as of ${page.dataAsOfDate ? new Date(page.dataAsOfDate).toLocaleDateString('en-IN') : 'N/A'}`);

    heading(doc, 'Snapshot');
    keyValue(doc, 'Locality Score', page.snapshot?.localityScore);
    keyValue(doc, 'Market Stage', page.snapshot?.marketStage);
    keyValue(doc, 'Rental Demand', page.snapshot?.rentalDemand);
    keyValue(doc, 'Infrastructure Strength', page.snapshot?.infrastructureStrength);
    keyValue(doc, 'Best For', page.snapshot?.bestFor);

    heading(doc, 'Price Stats');
    keyValue(doc, 'Avg Price / sqft', formatPaise(page.stats?.avgPricePerSqftPaise));
    keyValue(doc, 'Range', page.stats?.minPricePerSqftPaise != null
      ? `${formatPaise(page.stats.minPricePerSqftPaise)} – ${formatPaise(page.stats.maxPricePerSqftPaise)}`
      : null);
    keyValue(doc, 'Change (last month)', page.stats?.priceChangeLastMonthPct != null ? `${page.stats.priceChangeLastMonthPct}%` : null);
    keyValue(doc, 'Median Price', formatPaise(page.stats?.medianPricePaise));
    keyValue(doc, 'Avg Rental Yield', page.stats?.avgRentYieldPct != null ? `${page.stats.avgRentYieldPct}%` : null);
    keyValue(doc, 'Live Listings', page.stats?.inventoryLive?.total);
    keyValue(doc, 'Added This Week', page.stats?.inventoryLive?.addedThisWeek);

    if (page.investmentScore) {
      heading(doc, 'Investment Score');
      keyValue(doc, 'Overall', page.investmentScore.overall);
      const factors = page.investmentScore.factors || {};
      Object.entries(factors).forEach(([k, v]) => keyValue(doc, k, v));
    }

    if (page.buyVsRent) {
      heading(doc, 'Buy vs Rent');
      keyValue(doc, 'Buyer Demand', page.buyVsRent.buyerDemandPct != null ? `${page.buyVsRent.buyerDemandPct}%` : null);
      keyValue(doc, 'Seller Demand', page.buyVsRent.sellerDemandPct != null ? `${page.buyVsRent.sellerDemandPct}%` : null);
      keyValue(doc, 'Rental Yield', page.buyVsRent.rentalYieldPct != null ? `${page.buyVsRent.rentalYieldPct}%` : null);
      keyValue(doc, 'Rent Trend (1y)', page.buyVsRent.rentTrend1yPct != null ? `${page.buyVsRent.rentTrend1yPct}%` : null);
    }

    if (page.prosAndCons) {
      heading(doc, 'Pros & Cons');
      (page.prosAndCons.pros || []).forEach((p) => doc.text(`+ ${p}`));
      (page.prosAndCons.cons || []).forEach((c) => doc.text(`- ${c}`));
    }

    if (page.connectivity) {
      heading(doc, 'Connectivity');
      keyValue(doc, 'Metro', (page.connectivity.metro || []).join(', ') || null);
      keyValue(doc, 'Airports', (page.connectivity.airports || []).join(', ') || null);
      keyValue(doc, 'Major Roads', (page.connectivity.majorRoads || []).join(', ') || null);
    }

    if (Array.isArray(page.infrastructureProjects) && page.infrastructureProjects.length) {
      heading(doc, 'Upcoming Infrastructure');
      page.infrastructureProjects.forEach((proj) => {
        doc.text(`• ${proj.name} (${proj.category || ''}) — ${proj.status || ''}${proj.year ? `, ${proj.year}` : ''}`);
      });
    }

    if (Array.isArray(page.topVerifiedPicks) && page.topVerifiedPicks.length) {
      heading(doc, 'Top Verified Picks');
      page.topVerifiedPicks.forEach((p) => {
        doc.text(`• ${p.project} — ${p.bedroomConfig || ''} — ${formatPaise(p.price)} (${p.area ?? '?'} ${p.areaUnit || ''})`);
      });
    }

    doc.moveDown(1).fontSize(8).fillColor('#999')
      .text('Generated by RealtyDoor. Figures are indicative and sourced from the latest available market data.', { align: 'center' });

    doc.end();
  });
}

module.exports = { buildLocalityReportPdf };
